### ISSUE TITLE
Should #repository be public?

### ISSUE THREAD

**Issue by terrellt** [ActiveTriples/ActiveTriples#106]
I've run into this a few times - trying to get an object's repository. Is it private for a reason?

**Comment by no-reply** [comment]
I'm working on abstracting `repository` out to swappable persistence strategies.  I think I will make it public on the strategy instance; but this will likely not be a method on `Resource`/`RDFSource` going forward.

**Comment by elrayle** [comment]
Hey Tom,


Can you expand on what you are thinking about here?  What other persistence strategies are you looking to support?  I have been pondering how to get the ontology gems to be capable of writing to a triples store (current implementation) and/or capable of persisting to Fedora, depending on what repository is currently being used.  I have no more details because I haven't pursued this beyond thinking it would be cool.


Lynette

**Comment by no-reply** [comment]
@elrayle I'm absolutely considering an `LDPStrategy` and a `RepositoryProjectionStrategy` that avoids the need to call `persist!`.

Mostly that work is an attempt to get objects that are responsible for persistence, specifically, so we can think better about how they act.  Currently, persistence is a little too much entwined with the rest of `Resource` to do any major work on it--so my main goal is to fix that.

**Comment by elrayle** [comment]
RE: avoid the need to call persist!, are you looking at every change automatically being persisted at the point the change occurs?

**Comment by no-reply** [comment]
Yes. That strategy would just be a `Graph` backed by a `Repository` in the way allowed by `RDF::Graph`.

**Comment by no-reply** [comment]
The aforementioned `PersistenceStrategy` changes are going in via #133.  I think that closes this issue, since `RDFSource` and `Resource` no longer have a `repository` directly.  The repository object is accessible via the resource's `RepositoryStrategy` when it is used.
