### ISSUE TITLE
reciprocal relationships hang when set

### ISSUE THREAD

**Issue by elrayle** [ActiveTriples/ActiveTriples#147]
See change to [resource_spec.rb](https://github.com/ActiveTriples/ActiveTriples/compare/reciprocal_relationships?diff=split&name=reciprocal_relationships) to add setting of a reciprocal relationship.  It hangs during the process of setting the reciprocal relationship.

```
      document1.creator = [person1, person2]         # OK
      document2.creator = person1                    # OK
      person1.publications = [document1,document2]   # Hangs
```
A simpler version also hangs.
```
      document1.creator = person1                    # OK
      person1.publications = document1               # Hangs
```

**Comment by elrayle** [comment]
Added [new test](https://github.com/ActiveTriples/ActiveTriples/blob/f35e9b12147931783c0dc47b41c761330ea129bf/spec/single_tests/reciprocal_spec.rb) to just test this issue to make it easier to track down the problem.

**Comment by elrayle** [comment]
I traced the problem to ActiveTriples::ParentStrategy#final_parent. The value of current alternates between document1 and person1 ending up in an infinite loop.

**Comment by jcoyne** [comment]
ActiveFedora uses https://github.com/projecthydra/active_fedora/blob/master/lib/active_fedora/autosave_association.rb#L101 to work around this problem

**Comment by elrayle** [comment]
I was thinking about doing something similar.  When there is a loop, what do you consider the final_parent... the one just before the original or the original itself?

if  A -> B -> C -> A
is C the final parent?  or is A?

**Comment by elrayle** [comment]
I've been playing around with possible fixes including the following change to final_parent.  It doesn't work, as some of the statements are deleted and never re-inserted.

https://gist.github.com/elrayle/56cedbefe24ed5865719

@no-reply or @terrellt, can you provide an explanation of the philosophy behind [persist! (line 70)](https://github.com/ActiveTriples/ActiveTriples/blob/master/lib/active_triples/persistence_strategies/parent_strategy.rb#L71-L73) calling erase_old_resource, which removes all statements on the parent, and then pushing the obj being persisted onto the final_parent?


How do you think the following two scenarios should work?

```
#simple reciprocal relationship
document1.creator = person1
person1.publications = document1
```
NOTE: With the gist, all statements for document1 are deleted by erase_old_resource when person1.publications is executed and never added back.

```
#complex intertwined relationships
document1.creator = person1
person1.publications = document1
person1.knows = person2
```
NOTE: Gets even more complex with relationships like this example.

**Comment by elrayle** [comment]
From a conversation with Tom, I understand that ParentStrategy is not designed to handle the following  common patterns...  (NOTE: I am using generic predicate relatesTo for all examples.)

* A relatesTo B && B relatesTo A
* A relatesTo B && B relatesTo C && C relatesTo A
* A relatesTo B && A relatesTo C && B relatesTo C

There are three files under persistence_strategies:

* parent_strategy.rb
* persistence_strategy.rb
* repository_strategy.rb

Are one of the strategies more appropriate for the patterns described above?
Are there other strategies planned?

**Comment by no-reply** [comment]
The email mentioned by @elrayle previously reads:

> I can't address this completely right now, as I'm on vacation, but I'll take a first pass at it:
>
> There's some continued articulation needed about how we expect RDFSource's to persist.  Some of the problems we've seen with this change are resulting from the lack of clear behavior before these changes (resources persisted to `parent` in certain poorly-defined cases).
>
> `ParentStrategy` allows a given RDFSource to be "embedded" within another (another way of saying this is that the child RDFSource's underlying graph is a subgraph of the parent's).  The persistence of the child is then tied directly to the persistence of the parent; i.e. changes to the child's graph are reflected in the parent's graph when you call `persist!` on the child, and will only reach the storage layer when some `parent` with a different strategy is persisted. Circular parent/child relationships should be disallowed, since this would result in both graphs circularly persisting to each other's in-memory graphs.
>
> Again, there's more work to do here. What I described above is more or less what the old code did, except when it didn't. The effort, I think, needs to be toward a clear and consistent behavior. I think we should probably revoke the 0.8.x releases until that can be completed. I feel like they came out prematurely, in retrospect.  (I guess this is why we need tests that thoroughly specify behavior!)
> 
> I'd appreciate some help figuring out how embedded RDFSources should be have and/or feedback on the above description.

All of the existing persistence strategies will handle circular relations fine, the problem arises if you try to employ circular persistence. If none of the resources actually persists anywhere but to another in-memory resource, there is no place to persist in the end.

What `PersistenceStrategy` aims to do* is clarify existing patterns of persistence, while separating responsibilities and adding flexibility. There are a few places where the current code is broken, but I hope we can fix those up; my feeling is that the previous approaches were equally broken, with less clarity about what they were trying to do.

Previously, instances would persist to `:parent` in various odd cases, depending on how they were instantiated, and what you had done with them since. The state of affairs was enough of a mess that trying to duplicate the behavior with a different design pattern led to where we are now.

I'm coming back to this tomorrow; for now:

> Are one of the strategies more appropriate for the patterns described above?

Yes. If in any of those cases, B or C uses `RepositoryStrategy` (or any other method of persistence), then you can persist, e.g. as follows:

`A relatesTo B && B relatesTo C && C relatesTo A`
Persist A to B (i.e. A's graph is a subgraph of B's), persist B to C (likewise), persist C to a Repository. The statement relating C to A can live in either A's graph or C's (or B's, for that matter).  In short, the relationships and the persistence aren't dependent on one another.

> Are there other strategies planned?

There are a couple I've discussed with various folks:

  - I'd like to create a generic LDP strategy to replace some mixin code in Krikri that muddles the interface (at DPLA we save LDP resources with `save`; `persist!` is a no-op that "persists" to an in-memory ephemeral repository).
  - @mjsuhonos has talked about creating a strategy for Mongoid.
  - I think it would be worth exploring whether `ActiveFedora` should use a strategy; but I'm out of the loop on the state of the art there.

Hope this helps! I'll try to work on this a bit on the weekend, and will keep you in the loop.

**Comment by mjsuhonos** [comment]
>   - @mjsuhonos has talked about creating a strategy for Mongoid.

For anyone still interested, I've started this [branch here](https://github.com/ladder/ActiveTriples/tree/mongoid-strategy), but the bulk is in [MongoidStrategy](https://github.com/ladder/ActiveTriples/blob/mongoid-strategy/lib/active_triples/persistence_strategies/mongoid_strategy.rb).  It's early days yet, but it seems to behave (and frankly, integrate) fairly well.  I'm a bit excited.

**Comment by no-reply** [comment]
The issue as described is patched in the latest `develop`. A deeper solution is proposed in #184.
