### ISSUE TITLE
Should RDFSource/Resource Classes Inherit Configuration from their Parents?

### ISSUE THREAD

**Issue by no-reply** [ActiveTriples/ActiveTriples#158]
#154 calls for inheritance of configuration on RDF type, base URI, and persistence; per: https://github.com/ActiveTriples/ActiveTriples/blob/compatibility_tests/spec/compatibility_tests/inherited_configuration_spec.rb#L27-L38

Things worked like this prior to 0.7.0, but disappeared with the introduction of `RDFSource` and the move away from subclassing as the main paradigm. It wasn't a tested or documented feature.

To me it's an open question: _should_ classes inherit their configuration and/or properties from their parents? If so, which parts?

**Comment by no-reply** [comment]
This deals with one of the issues documented by #154.

**Comment by jcoyne** [comment]
I think it is important to inherit type (so long as the subclass can set its own). I don't think I care about the others.

**Comment by no-reply** [comment]
:+1:. Type is the most attractive to inherit, and also the most problematic, since there is a type -> class registry.

This exacerbates the problems discussed in the various issues linked from #159.

**Comment by mjsuhonos** [comment]
IMO this question sort of becomes "how closely do we want RDFSource models to behave like their respective ontologies"; ie. I dealt with this issue a lot when trying to model MODSRDF 1:1 in Ladder, because of how extensively it uses subclassing.

Full configuration inheritance would open the possibility of, eg. parsing an OWLDoc and generating RDFSource classes (similar to vocab-fetch), but I don't know how strong this use case is.

Alternately, instead of automatic inheritance, what about an explicit class method that takes a list of configuration keys to inherit?  eg. `#inherit! :type, :base_uri`

**Comment by no-reply** [comment]
The branch https://github.com/ActiveTriples/ActiveTriples/tree/feature/type-inheritance includes the proposed type inheritance.

I'm looking at writing tests and documentation for `rdf:type` -> Ruby class relationships. I'll report back when I know more.
