### ISSUE TITLE
Release a new 0.8 version.

### ISSUE THREAD

**Issue by jcoyne** [ActiveTriples/ActiveTriples#176]
It's been 7 months since the last version.  There is no released version of 0.8 that works with rdf 1.99

**Comment by no-reply** [comment]
It would be nice to get https://github.com/ActiveTriples/ActiveTriples/pull/159 (or something similar) in; but I think it's still somewhat controversial.

**Comment by jcoyne** [comment]
@no-reply I'm pretty sure that's all due to MODS. :cry:

**Comment by cbeer** [comment]
Bump?

**Comment by elrayle** [comment]
I am actively working on a solution to #194.  Moving to parent_strategy for rdf_sources created via class_name on property definitions has changed the behavior this had in pre-0.8 releases.  It would be good to have this in the latest release.  Or we could have another quick release after this issue is resolved.

**Comment by elrayle** [comment]
0.8.2 was released last week.
