### ISSUE TITLE
Make `data` accessible from an AT::Resource

### ISSUE THREAD

**Issue by tpendragon** [ActiveTriples/ActiveTriples#222]
Should we open up the `graph` method or just delegate `data` down?

**Comment by no-reply** [comment]
If we go with making `#graph` public, I want to be careful about the contract for the method. 

I'm reluctant to guarantee the return value as an `RDF::Graph`, thinking of the changes in https://github.com/ActiveTriples/ActiveTriples/tree/feature/tx-parent. `RDF::Queryable + RDF::Mutable`, could work; but I think you also want a promise that `#data` will be an `RDF::Repository`... ...thinking about this.

It might be better to expose the underlying `Repository` more directly, but that feels pretty hacky.

In projecthydra/active_fedora#1109, is `@ldp_source.graph` an AT RDFSource? I wonder if there isn't a cleaner pattern we could adopt.

In any case, I'm okay making `#graph` public as a stop gap if  a solution isn't making itself obvious soon.

**Comment by tpendragon** [comment]
`@ldp_source.graph` is an AT::RDFSource, yes.

**Comment by no-reply** [comment]
@tpendragon my changes in the https://github.com/ActiveTriples/ActiveTriples/tree/feature/tx-parent branch make some progress on this. `#graph` is public, but it's return value may be an `RDF::Transaction`. 

I'm still thinking about the implications of this, but we'll want to work a bit to refine the APIs if you're still eyeing projecthydra/active_fedora#1111.

**Comment by no-reply** [comment]
@tpendragon i think this might be closed for your purposes.

Ignoring Demeter, you have `@ldp_source.graph.data`. For your cases, this will return an `RDF::Repository`. 

For objects using `ParentStrategy`, `#graph` can return a `BufferedTransaction`, which implements the `Transaction`, rather than `Graph`. I suspect you'll get an error if that happens, which should be fine. 

If you'd like to scope out a builder that can handle all of this cleanly, I'm :+1: on that. Otherwise, what do you think about calling this closed?
