### ISSUE TITLE
Array.wrap ActiveTriples::Relation no longer works correctly in 0.11.0

### ISSUE THREAD

**Issue by jcoyne** [ActiveTriples/ActiveTriples#252]
``` ruby
(byebug) thing
[]
(byebug) thing.class
ActiveTriples::Relation
(byebug) Array.wrap(thing)
[[]]
```

**Comment by jcoyne** [comment]
Dues to removing `to_ary` here: https://github.com/ActiveTriples/ActiveTriples/commit/46e646460d3147fedbdc48890bd4b4fb3f1323da.  Would anyone care if I re-added it?

**Comment by jcoyne** [comment]
Here's another problem:
```
       no implicit conversion of ActiveTriples::Relation into Array
```
when doing `Array + ActiveTriples::Relation`

**Comment by no-reply** [comment]
I have mixed feelings... 

On the one hand, I think the behavior described is technically correct (which is my favorite kind of correct). The most helpful guidance I've seen on when to provide implicit conversions is [your type should implement it only if it sees itself as “kind of” target type](https://zverok.github.io/blog/2016-01-18-implicit-vs-expicit.html). I don't think we meet that bar, since we're not ordered, and don't behave like an `Array` in other ways.

On the other hand, I can't foresee any problem with just implementing it (which isn't to say that none exist), if it helps conform to Rails-y expectations.

**Comment by jeremyf** [comment]
We have a known downside for not treating it as an array. And a theoretical/semantic potential for downsides if we do treat it as an array (for Coercion purposes).

It sounds like a more "formal" solution is that we provide a presenter wrapper around these relations. But that might be very heavy handed.

**Comment by no-reply** [comment]
Leaning toward simply adding `#to_ary` back, though I have a creeping feeling that we'll come to regret it. I'm +0.

I'd like to get @tpendragon's input before moving ahead.

**Comment by no-reply** [comment]
Proposing to close this. ActiveFedora seems to be doing okay without this method at this point.
