### ISSUE TITLE
Time for version 1.0?

### ISSUE THREAD

**Issue by dchandekstark** [ActiveTriples/ActiveTriples#92]
Given the reliance of ActiveFedora and Hydra on AT, I think it would be beneficial to begin using major versions to signal backwards incompatible changes.

**Comment by no-reply** [comment]
We have an ongoing commitment to backwards compatibility on pre-1.0 minor versions for exactly this reason.  

There are some fairly major changes we have slated for 1.0 (see: https://github.com/ActiveTriples/ActiveTriples/milestones/1.0), and I would really like to see at least the property->predicate issue resolved before a 1.0 release.  

My hope had been to start work on this around now, but it looks like it will likely have to wait until after Code4Lib.  

Thoughts?

**Comment by dchandekstark** [comment]
I confess to being confused about about the combined changes in AF and AT which pushed us to AF8.  It does appear that aspects of the public API have changed since AT 0.2.3 which break backward compatibility.  No argument since it's 0.x, but thought it was worth raising the question.

**Comment by no-reply** [comment]
Yeah, it *is* changing rapidly, which is one reason I'm reluctant to move to 1.0.  I think we would likely be on 3.x or 4.x very quickly.  The minor versions have been studiously bumped for breaking changes since before Hydra Connect, and we're currently on 0.5.0.

What I would really like to do is make a directed push to 1.0, and document it well.

**Comment by dchandekstark** [comment]
Yeah, I get it.  Thanks for the (no-)replies. :)  I'll close the issue.

**Comment by no-reply** [comment]
And thank you for raising it.  It's a good reminder that this push needs to be high on my priority list.
